### ISSUE TITLE
Cloudflarebeat throws panic when processing data.

### ISSUE THREAD

**Issue by kegsofduff** [hartfordfive/cloudflarebeat#14]
Hi, 
I built cloudflarebeat on CentOS release 6.8 and have it running connected to Cloudflare. After a few minutes of running it will attempt to process some data and then throw a panic and crash. I'm hoping you can help out. 

Thanks, 

Debug output:

```
2017/03/10 20:24:43.076346 event.go:54: DBG  Dropped nil value from event where key=edge.rateLimitRuleId
2017/03/10 20:24:43.076361 event.go:54: DBG  Dropped nil value from event where key=edgeRequest.headers
2017/03/10 20:24:43.076371 event.go:54: DBG  Dropped nil value from event where key=edgeResponse.headers
2017/03/10 20:24:43.076380 event.go:54: DBG  Dropped nil value from event where key=edgeResponse.setCookies
2017/03/10 20:24:43.076396 event.go:54: DBG  Dropped nil value from event where key=clientRequest.cookies
2017/03/10 20:24:43.076409 event.go:54: DBG  Dropped nil value from event where key=cache.headers
2017/03/10 20:24:43.076427 event.go:54: DBG  Dropped nil value from event where key=cache.externalPort
2017/03/10 20:24:43.076439 event.go:54: DBG  Dropped nil value from event where key=cache.cacheFileKey
2017/03/10 20:24:43.076454 event.go:54: DBG  Dropped nil value from event where key=unstable
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 51 [running]:
panic(0xa2a0e0, 0xc420158780)
    /home/kegsofduff/repos/go/src/runtime/panic.go:500 +0x1a1
github.com/hartfordfive/cloudflarebeat/cloudflare.BuildMapStr(0xc4205b49c0, 0x129f)
    /home/kegsofduff/repos/go/src/github.com/hartfordfive/cloudflarebeat/cloudflare/utils.go:171 +0x644c
github.com/hartfordfive/cloudflarebeat/cloudflare.(*LogConsumer).PrepareEvents(0xc420223700)
    /home/kegsofduff/repos/go/src/github.com/hartfordfive/cloudflarebeat/cloudflare/logconsumer.go:139 +0x65c
created by github.com/hartfordfive/cloudflarebeat/beater.(*Cloudflarebeat).DownloadAndPublish
    /home/kegsofduff/repos/go/src/github.com/hartfordfive/cloudflarebeat/beater/cloudflarebeat.go:142 +0xc1
```

**Comment by hartfordfive** [comment]
Hi @kegsofduff,

Which tag/commit SHA are you using?

**Comment by hartfordfive** [comment]
Hi @kegsofduff, any updates on this?
